import { Link } from 'react-router-dom';
import { ArrowUpRight } from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, BarChart, Bar, PieChart, Pie, Cell } from 'recharts';
import { useApp } from '../store/useApp';
import { calculateStats } from '../lib/statsCalculator';
import { addDays, formatDate } from '../lib/dates';

export function StatsPage() {
  const { workoutLogs, todayDateStr: today } = useApp();
  const stats = calculateStats(workoutLogs, today);
  const categories = stats.categoryDistributionChart.filter(c => c.value > 0);
  const measured = stats.painVsDifficultyChart.some(p => p.dor !== null || p.dificuldade !== null);
  return <div className="stack"><header className="page-heading"><p className="eyebrow">A tua evolução</p><h1>Pequenos passos, visíveis</h1><p className="muted">Um retrato dos teus registos, ao teu ritmo.</p></header>
    <p className="small muted">Últimos 7 dias: {formatDate(addDays(today, -6))} a {formatDate(today)}.</p>
    <div className="grid-2"><section className="card"><p className="eyebrow">Dias concluídos</p><p className="stat-number">{stats.weeklyCompleted}<span className="small muted"> / 7</span></p><p className="small muted">no período indicado</p></section><section className="card"><p className="eyebrow">Dor média</p><p className="stat-number">{stats.avgPainPast7Days === null ? '—' : stats.avgPainPast7Days}<span className="small muted"> / 10</span></p><p className="small muted">{stats.avgPainPast7Days === null ? 'Sem medições no período' : 'apenas medições registadas'}</p></section></div>
    <div className="callout">{stats.simpleInsight}</div>
    <section className="card stack"><div className="split"><h2>Conforto e esforço</h2><span className="pill">14 dias</span></div><p className="small muted">{stats.painTrendText}</p>
      {measured ? <><div className="chart" role="img" aria-label="Dor e esforço registados nos últimos 14 dias, numa escala de zero a dez"><ResponsiveContainer width="100%" height="100%"><LineChart data={stats.painVsDifficultyChart} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eadee2" /><XAxis dataKey="dayLabel" tick={{ fontSize: 12 }} /><YAxis domain={[0, 10]} tick={{ fontSize: 12 }} /><Tooltip /><Line name="Dor" dataKey="dor" stroke="#78526f" strokeWidth={2} connectNulls={false} isAnimationActive={false} /><Line name="Esforço" dataKey="dificuldade" stroke="#528373" strokeWidth={2} connectNulls={false} isAnimationActive={false} /></LineChart></ResponsiveContainer></div><div className="cluster small"><span>● Dor · ameixa</span><span style={{ color: '#426c5d' }}>● Esforço · verde</span></div><details><summary>Ver valores registados</summary><div style={{ overflowX: 'auto', marginTop: 12 }}><table className="data-table"><thead><tr><th>Dia</th><th>Dor / 10</th><th>Esforço / 10</th></tr></thead><tbody>{stats.painVsDifficultyChart.map(row => <tr key={row.dayLabel}><td>{row.dayLabel}</td><td>{row.dor ?? 'Não registado'}</td><td>{row.dificuldade ?? 'Não registado'}</td></tr>)}</tbody></table></div></details></> : <div className="callout neutral">Ainda não há medições. Marcar um exercício como concluído não preenche dor ou esforço automaticamente.</div>}
    </section>
    <div className="content-grid stack"><section className="card stack"><h2>Movimento ao longo do tempo</h2><p className="small muted">Quatro períodos de 7 dias. Cada etiqueta indica o início do período.</p><div className="chart" role="img" aria-label="Número de dias com exercício concluído por período de sete dias"><ResponsiveContainer width="100%" height="100%"><BarChart data={stats.weeklyWorkoutsChart} margin={{ left: -25 }}><XAxis dataKey="weekLabel" tick={{ fontSize: 12 }} /><YAxis domain={[0, 7]} allowDecimals={false} tick={{ fontSize: 12 }} /><Tooltip /><Bar dataKey="treinos" name="Dias concluídos" fill="#78526f" radius={[8, 8, 0, 0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></div><p className="small muted">{stats.weeklyWorkoutsChart.map(w => w.weekLabel + ': ' + w.treinos + ' dias').join(' · ')}</p></section>
    <section className="card stack"><h2>Os teus movimentos</h2><p className="small muted">Categorias de todo o histórico de exercícios concluídos. Postura é agrupada em mobilidade.</p>{categories.length ? <><div className="chart" role="img" aria-label="Distribuição das categorias de exercícios concluídos"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius={65} outerRadius={90} paddingAngle={4} isAnimationActive={false}>{categories.map(c => <Cell key={c.name} fill={c.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div>{categories.map(c => <div className="split small" key={c.name}><span>{c.name}</span><strong>{c.value}</strong></div>)}</> : <p className="callout neutral">As categorias aparecem quando guardares o primeiro exercício concluído.</p>}</section></div>
    <section className="card sage split"><div><h3>{stats.totalCompleted} dias no histórico</h3><p className="small">Sequência atual: {stats.streak} dias.</p></div><Link className="icon-button" aria-label="Abrir calendário" to="/calendar"><ArrowUpRight size={20} /></Link></section>
  </div>;
}

